services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      JENKINS_USER: "admin"
      JENKINS_PASS: "password"

volumes:
  jenkins_data:
    driver: local